# Generated by Django 4.2.7 on 2024-02-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название валюты')),
                ('charcode', models.CharField(max_length=3, unique=True, verbose_name='Код валюты')),
                ('date', models.DateField(auto_now=True, unique=True, verbose_name='Дата')),
                ('rate', models.PositiveIntegerField(verbose_name='Курс к рублю')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
    ]
