# Generated by Django 4.2.7 on 2024-02-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Дата'),
        ),
    ]
